# Generated by Django 5.2.8 on 2026-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_pharmacy_latitude_pharmacy_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(default='Tabletkalar', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
