# Generated by Django 5.2.8 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_medicine_category_medicine_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='work_hours',
            field=models.CharField(blank=True, default='24 саат', max_length=50),
        ),
    ]
